project:
  render: # Specific pages on development
    - "**/*.qmd"
    # Don't render specific pages or folders:
    # - trial/testimonies/suspect/guran_enes/testimony.qmd
    # - "!trial/**"
    # - "!blog/**"
