project:
  post-render:
    - ../shared/bash/sync-tr.sh
    - ../shared/python/render_timer.py end
    - ../shared/bash/deploy.sh
  render:
    - "**/*.qmd"
    - "!test.qmd"    # Don't render test*.qmd at the root
    - "!*-test.qmd"

website:
  google-analytics: "G-58C9MLB2WP" # https://analytics.google.com
